---
abstract: 'Role for daemonizing your Moose based application'
author:
  - 'Chris Prather  C<< <perigrin@cpan.org> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Daemonize
no_index:
  directory:
    - examples
    - inc
    - t
    - examples
    - examples
requires:
  Moose: 0.33
  MooseX::Getopt: 0.07
  MooseX::Types::Path::Class: 0
version: 0.07
