--- 
abstract: "provides a Role that daemonizes your Moose based "
author: 
  - Chris Prather  C<< <perigrin@cpan.org> >>
build_requires: 
  File::Slurp: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Daemonize
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  Carp: 0
  File::Pid: 0
  Moose: 0.2
  MooseX::Getopt: 0
  Proc::Daemon: 0
version: 0.05
