---
abstract: 'Role for daemonizing your Moose based application'
author:
  - 'Chris Prather  C<< <chris@prather.org >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Daemonize
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  File::Path: 2.08
  Moose: 0.33
  MooseX::Getopt: 0.07
  MooseX::Types::Path::Class: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.moose.perl.org/MooseX-Daemonize.git
version: 0.16
